In [198]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from collections import Counter

In [199]:
df_il = pd.read_csv('final_merge_il.csv')
df_ca = pd.read_csv('final_merge_ca.csv')
df_ny = pd.read_csv('final_merge_ny.csv')

/var/folders/6l/cmpq4f_96xv7_3p8k362lbnr0000gn/T/ipykernel_36855/2767464834.py:2: DtypeWarning: Columns (10,11,16,17,22,23,28,29,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,100,101,102,103,104,105,106,107,108,109,110,111,118,119,122,123,124,125,128,129,136,137,138,139,142,143,144,145,190,191,192,193,226,362,363,366,367,370,371,374,375,378,379,382,383,386,387,390,391,394,395,398,399,402,403,406,407,410,411,414,415,418,419,420,421,426,427,430,431,434,435,438,439,446,447,450,451,470,471,474,475,478,479,482,483,486,487,490,491,494,495,498,499,502,503,506,507,510,511,514,515,518,519,522,523,526,527,530,531,534,535,538,539,542,543,546,547,550,551,554,555,558,559,562,563,566,567,570,571,574,575,578,579,582,583,590,591,594,595,598,599,602,603,606,607,610,611,618,619,622,623,626,627,630,631,634,635,638,639,642,643,646,647,650,651,654,655,658,659,662,663,666,667,670,671,674,675) 

In [200]:
print(df_il.shape)
print(df_ca.shape)
print(df_ny.shape)

(1319, 682)
(2346, 683)
(2167, 681)


New York City (Bronx County, Kings County, New York County, Queens County, Richmond County)

In [338]:
df_ny = df_ny[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE", "target"]]
df_ny.replace(to_replace = {'250,000+': '250000', '2,500-': '2500', '-': np.nan}, inplace=True)
df_ny = df_ny.dropna().astype(float)

In [339]:
X = df_ny[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE"]].to_numpy()
y = df_ny['target'].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [203]:
Counter(y)

Counter({0.0: 1262, 1.0: 90})

Standard Implementation

In [208]:
lgr = LogisticRegression(random_state=0, max_iter=1000).fit(X_train, y_train) # max_iter=1000

In [209]:
np.round(lgr.score(X_test, y_test),3)

0.931

In [210]:
lgr.predict(X_test[:10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [211]:
np.round(lgr.predict_proba(X[:10]),3)

array([[0.961, 0.039],
       [0.958, 0.042],
       [0.905, 0.095],
       [0.912, 0.088],
       [0.872, 0.128],
       [0.882, 0.118],
       [0.863, 0.137],
       [0.913, 0.087],
       [0.884, 0.116],
       [0.936, 0.064]])

In [212]:
np.round(lgr.predict_proba(X[12, :].reshape(1, -1)),3)

array([[0.875, 0.125]])

In [213]:
lgr.classes_

array([0., 1.])

In [214]:
np.round(lgr.coef_,3)

array([[ 0.003, -0.   , -0.   , -0.   , -0.014, -0.012]])

In [215]:
np.round(lgr.intercept_,3)

array([-0.886])

In [216]:
lgr.n_features_in_

6

In [217]:
lgr.n_iter_

array([137], dtype=int32)

In [ ]:
for f_id in np.argsort(lgr.coef_[0])[::-1][:6]:
    print("%.3f: %s" % (clf.coef_[0][f_id], features[f_id]))

Regularization, Solver, Class Weight

In [340]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1.0, max_iter=1000).fit(X_train, y_train)

In [341]:
np.round(lgr.score(X_test, y_test),3)

0.931

In [342]:
np.round(lgr.coef_,3)

array([[ 0.003, -0.   , -0.   , -0.   , -0.014, -0.012]])

In [343]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [344]:
np.round(lgr.score(X_test, y_test),3)

0.931

In [345]:
np.round(lgr.coef_,3)

array([[-0.013, -0.   , -0.   , -0.   , -0.006, -0.011]])

In [349]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [350]:
np.round(lgr.score(X_test, y_test),3)

0.931

In [351]:
np.round(lgr.coef_,3)

array([[-0.013, -0.   , -0.   , -0.   , -0.006, -0.011]])

In [352]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [353]:
np.round(lgr.score(X_test, y_test),3)

0.931

In [354]:
np.round(lgr.coef_,3)

array([[ 0.003, -0.   , -0.   , -0.   , -0.014, -0.012]])

In [355]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', class_weight='balanced', max_iter=1000).fit(X_train, y_train)

In [356]:
np.round(lgr.score(X_test, y_test),3)

0.52

In [361]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', class_weight={0.0: 0.1, 1.0: 0.9}, max_iter=1000).fit(X_train, y_train)

In [362]:
np.round(lgr.score(X_test, y_test),3)

0.771

In [377]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', class_weight={0.0: 0.3, 1.0: 0.7}, max_iter=1000).fit(X_train, y_train)

In [378]:
np.round(lgr.score(X_test, y_test),3)

0.931

Los Angeles (Los Angeles County)

In [379]:
df_ca = df_ca[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE", "target"]]
df_ca.replace(to_replace = {'250,000+': '250000', '2,500-': '2500', '-': np.nan}, inplace=True)
df_ca = df_ca.dropna().astype(float)

In [380]:
X = df_ca[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE"]].to_numpy()
y = df_ca['target'].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [220]:
Counter(y)

Counter({0.0: 1131, 1.0: 271})

Standard Implementation

In [222]:
lgr = LogisticRegression(random_state=0, max_iter=1000).fit(X_train, y_train) # max_iter=1000

In [223]:
np.round(lgr.score(X_test, y_test),3)

0.812

In [225]:
np.round(lgr.predict_proba(X_test[:10]),3)

array([[0.78 , 0.22 ],
       [0.715, 0.285],
       [0.858, 0.142],
       [0.914, 0.086],
       [0.89 , 0.11 ],
       [0.606, 0.394],
       [0.826, 0.174],
       [0.803, 0.197],
       [0.731, 0.269],
       [0.783, 0.217]])

In [226]:
lgr.classes_

array([0., 1.])

In [227]:
np.round(lgr.coef_,3)

array([[-0.026,  0.   , -0.   ,  0.   ,  0.006,  0.014]])

In [228]:
np.round(lgr.intercept_,3)

array([0.247])

In [229]:
lgr.n_features_in_

6

In [230]:
lgr.n_iter_

array([134], dtype=int32)

Regularization, Solver, Class Weight

In [381]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, max_iter=1000).fit(X_train, y_train)

In [382]:
np.round(lgr.score(X_test, y_test),3)

0.812

In [383]:
np.round(lgr.coef_,3)

array([[-0.026,  0.   , -0.   ,  0.   ,  0.006,  0.014]])

In [384]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [385]:
np.round(lgr.score(X_test, y_test),3)

0.812

In [386]:
np.round(lgr.coef_,3)

array([[-0.014, -0.   , -0.   ,  0.   , -0.002,  0.004]])

In [393]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [394]:
np.round(lgr.score(X_test, y_test),3)

0.812

In [395]:
np.round(lgr.coef_,3)

array([[-0.026, -0.   , -0.   ,  0.   ,  0.006,  0.014]])

In [399]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', class_weight='balanced', max_iter=1000).fit(X_train, y_train)

In [400]:
np.round(lgr.score(X_test, y_test),3)

0.584

In [401]:
np.round(lgr.coef_,3)

array([[-0.026,  0.   , -0.   ,  0.   ,  0.006,  0.014]])

In [426]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', class_weight={0.0: 0.7, 1.0: 0.3}, max_iter=1000).fit(X_train, y_train)

In [427]:
np.round(lgr.score(X_test, y_test),3)

0.812

Chicago (Cook County)

In [430]:
df_il = df_il[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE", "target"]]
df_il.replace(to_replace = {'250,000+': '250000', '2,500-': '2500', '-': np.nan}, inplace=True)
df_il = df_il.dropna().astype(float)

In [431]:
X = df_il[["S1501_C01_014E", "S1903_C02_001E", "S1903_C02_002E", "S1903_C02_003E", "DP05_0032PE", "DP05_0033PE"]].to_numpy()
y = df_il['target'].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [233]:
Counter(y)

Counter({0.0: 621, 1.0: 68})

Standard Implementaion

In [234]:
lgr = LogisticRegression(random_state=0, max_iter=1000).fit(X_train, y_train) # max_iter=1000

In [235]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [236]:
np.round(lgr.predict_proba(X_test[:10]),3)

array([[0.849, 0.151],
       [0.843, 0.157],
       [0.825, 0.175],
       [0.917, 0.083],
       [0.947, 0.053],
       [0.952, 0.048],
       [0.914, 0.086],
       [0.828, 0.172],
       [0.849, 0.151],
       [0.888, 0.112]])

In [238]:
np.round(lgr.coef_,3)

array([[-0.006,  0.   , -0.   , -0.   , -0.014,  0.003]])

In [239]:
np.round(lgr.intercept_,3)

array([-1.])

In [240]:
lgr.n_iter_

array([187], dtype=int32)

Regularization, Solver, Class Weight

In [440]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, max_iter=1000).fit(X_train, y_train)

In [441]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [442]:
np.round(lgr.coef_,3)

array([[-0.006,  0.   , -0.   , -0.   , -0.014,  0.003]])

In [443]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [444]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [445]:
np.round(lgr.coef_,3)

array([[-0.016,  0.   , -0.   , -0.   , -0.017,  0.001]])

In [446]:
lgr = LogisticRegression(random_state=0, penalty='l1', C=1000, solver='liblinear', max_iter=1000).fit(X_train, y_train)

In [447]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [448]:
np.round(lgr.coef_,3)

array([[-0.006,  0.   , -0.   , -0.   , -0.014,  0.003]])

In [485]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, solver='liblinear', class_weight={0.0:0.8, 1.0: 0.2}, max_iter=1000).fit(X_train, y_train)

In [486]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [487]:
np.round(lgr.coef_,3)

array([[-0.027,  0.   , -0.   , -0.   , -0.025, -0.004]])

In [492]:
lgr = LogisticRegression(random_state=0, penalty='l2', C=1000, solver='liblinear', class_weight={0.0:0.6, 1.0: 0.4}, max_iter=1000).fit(X_train, y_train)

In [493]:
np.round(lgr.score(X_test, y_test),3)

0.903

In [494]:
np.round(lgr.coef_,3)

array([[-0.019,  0.   , -0.   , -0.   , -0.02 , -0.001]])